# Generated by Django 5.1.2 on 2024-12-07 18:46

import django.db.models.deletion
import payment.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('tracing_code', models.TextField(default=payment.models.short_uuid, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=7)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('SUCCESS', 'success'), ('FAILED', 'failed'), ('CANCELED', 'canceled'), ('UNDER_REVIEW', 'under review'), ('REFUNDED', 'refunded'), ('EXPIRED', 'expired'), ('PROCESSING', 'processing'), ('DECLINED', 'declined')], default='PENDING', max_length=20)),
                ('gateway', models.CharField(choices=[('MELI', 'Meli'), ('SAMAN', 'Saman'), ('PASARGAD', 'Pasargad')], default='MELI', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
