# Generated by Django 5.1.2 on 2024-12-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0002_restaurant_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/restaurants'),
        ),
    ]
