# Generated by Django 5.1.2 on 2024-12-07 17:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resturant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, max_digits=7)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('discount', models.IntegerField(default=0, help_text='Discount percentage (0 to 100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('restaurants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='resturant.restaurant')),
            ],
        ),
    ]
