# Generated by Django 5.1.2 on 2024-12-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/foods'),
        ),
    ]
