# Generated by Django 5.1.2 on 2024-12-22 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='rate',
            field=models.FloatField(default=0, help_text='rate number (0 to 5)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
