# Generated by Django 5.1.2 on 2024-12-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_alter_basket_items'),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='basket', to='food.food'),
        ),
    ]
